<script setup lang="ts">
import { ref } from 'vue'
import type { PublishResult, TokenConfig } from '../lib/types.js'
import AppNotice from './AppNotice.vue'
import { buildPackageFiles } from '../lib/generatePackage.js'
import { fetchLicenseText } from '../lib/licenses.js'
import { createRepoAndPush } from '../lib/github.js'

const props = defineProps<{ config: TokenConfig; result: PublishResult }>()

const open = ref(false)
const token = ref('')
const repoName = ref(props.config.packageName)
const isPrivate = ref(false)
const busy = ref(false)
const error = ref<string | null>(null)
const doneUrl = ref<string | null>(null)
const progress = ref('')

async function push(): Promise<void> {
  busy.value = true
  error.value = null
  doneUrl.value = null
  try {
    const licenseText = await fetchLicenseText(props.config.license)
    const files = buildPackageFiles({
      config: props.config,
      licenseText: licenseText ?? undefined,
      result: props.result,
    })
    const res = await createRepoAndPush({
      token: token.value.trim(),
      repoName: repoName.value.trim(),
      description: `${props.config.name} (${props.config.symbol}) — Sui coin package`,
      isPrivate: isPrivate.value,
      files,
      commitMessage: 'Initial token package (generated by Token Deployer)',
      onProgress: (d, t) => (progress.value = `Pushing files… ${d}/${t}`),
    })
    doneUrl.value = res.htmlUrl
  } catch (e) {
    error.value = e instanceof Error ? e.message : String(e)
  } finally {
    // Never retain the token beyond a single attempt — clear it whether the push
    // succeeded or failed (a failed push previously left it in the input/memory).
    token.value = ''
    busy.value = false
    progress.value = ''
  }
}
</script>

<template>
  <div>
    <button type="button" :aria-expanded="open" @click="open = !open">
      {{ open ? '▾' : '▸' }} Create a GitHub repo (optional)
    </button>

    <div v-if="open" class="card" style="margin-top: 0.5rem">
      <p v-once class="hint">
        Uses your <strong>own</strong> GitHub token — the repo is created in your account and this
        site's servers are never involved. The token is sent only to
        <span class="mono">api.github.com</span> over HTTPS, is never stored or logged, and is
        cleared as soon as the push finishes. Use a fine-grained token with "Contents" and
        "Administration" write access, or a classic token with the
        <span class="mono">repo</span> scope.
      </p>

      <label for="gh-repo">Repository name</label>
      <input id="gh-repo" v-model="repoName" autocomplete="off" />

      <label for="gh-token">GitHub token</label>
      <input
        id="gh-token"
        v-model="token"
        type="password"
        autocomplete="off"
        spellcheck="false"
        placeholder="github_pat_… or ghp_…"
      />

      <label style="font-weight: 400; margin-top: 0.75rem">
        <input type="checkbox" v-model="isPrivate" style="width: auto" /> Make the repository
        private
      </label>

      <div class="row" style="margin-top: 0.75rem">
        <button type="button" class="primary" :disabled="busy || !token || !repoName" @click="push">
          <span v-if="busy" class="spinner" aria-hidden="true"></span> Create repo &amp; push
        </button>
        <span v-if="progress" class="hint" aria-live="polite">{{ progress }}</span>
      </div>

      <AppNotice v-if="error" type="error">{{ error }}</AppNotice>
      <AppNotice v-if="doneUrl" type="ok">
        Pushed: <a :href="doneUrl" target="_blank" rel="noopener noreferrer">{{ doneUrl }}</a>
      </AppNotice>
    </div>
  </div>
</template>
